hmrc/hec-applicant-frontend

app/uk/gov/hmrc/hecapplicantfrontend/config/EnrolmentConfig.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/StartController.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/StartControllerSpec.scala

HEC-779: take NINO enrolment into account for SA individuals with org accounts

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxSituationController.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxSituationControllerSpec.scala

Display only the relevant tax situation options for the `/tax-situation` route in `TaxSituation.scala.html` based on the licence type selected.
For `DriverOfTaxisAndPrivateHires`, display all options.
For all other licence types, display only `SA` and `NotChargeable` options.

Display only relevant tax situation options based on licence type

---

app/uk/gov/hmrc/hecapplicantfrontend/config/AppConfig.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/SAController.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/SautrNotFound.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/SAControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala

Details in ticket - https://jira.tools.tax.service.gov.uk/browse/HEC-986

HEC-986 SAUTR not found page

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/SAController.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/NoReturnFound.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/SAControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala

Details in ticket - https://jira.tools.tax.service.gov.uk/browse/HEC-987

HEC-987 No SA return found page

---

app/uk/gov/hmrc/hecapplicantfrontend/models/TaxDetails.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckService.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/CheckYourAnswers.scala.html
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/connectors/HECConnectorImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CheckYourAnswersControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckServiceImplSpec.scala

Details in ticket - https://jira.tools.tax.service.gov.uk/browse/HEC-1015
This has been branched off of [HEC-985 PR](https://github.com/hmrc/hec-applicant-frontend/pull/29), so will rebase once that's in, but is ready for review
Note: waiting on `screenReaderText` confirmation

HEC-1015 Display SA income declared answer in CYA page

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNController.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
conf/app.routes
test/uk/gov/hmrc/hecapplicantfrontend/controllers/EntityTypeControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala

ticket -> https://jira.tools.tax.service.gov.uk/browse/HEC-1044

HEC-1044-crn page after entity page

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/uk/gov/hmrc/hecapplicantfrontend/config/AppConfig.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/ConfirmIndividualDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxChecksListController.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/ConfirmIndividualDetails.scala.html
app/uk/gov/hmrc/hecapplicantfrontend/views/Layout.scala.html
app/uk/gov/hmrc/hecapplicantfrontend/views/TaxCheckComplete.scala.html
app/uk/gov/hmrc/hecapplicantfrontend/views/TaxChecksList.scala.html
app/uk/gov/hmrc/hecapplicantfrontend/views/components/CopyButton.scala.html
app/uk/gov/hmrc/hecapplicantfrontend/views/components/TaxCheckCodeDetails.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/ConfirmIndividualDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/LicenceDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxChecksListControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala

Details in ticket - [HEC-1099](https://jira.tools.tax.service.gov.uk/browse/HEC-1099)

HEC-1099 tax check codes listing page

---

conf/messages

Fixed message as pointed out [here](https://jira.tools.tax.service.gov.uk/browse/HEC-1099?focusedCommentId=1451709&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1451709)

HEC-1099 Fix expiry date message

---

conf/messages

https://jira.tools.tax.service.gov.uk/browse/HEC-1176 <-- ticket to do this

update service name

---

project/AppDependencies.scala
test/uk/gov/hmrc/hecapplicantfrontend/repos/MongoSupportSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/repos/SessionStoreImplSpec.scala

Looks like we forgot to change hmrc mongo repo changes for test cases. Included that change too here and in hec &LB as well

Hec 1398 lib upgrade

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxSituationController.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/HECSession.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/TaxDetails.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckService.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/TaxSituation.scala.html
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/connectors/HECConnectorImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/EntityTypeControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/LicenceDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxCheckCompleteControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxChecksListControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxSituationControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/models/HECTaxCheckDataSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/utils/Fixtures.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1420

Hec 1420 rity

---

app/uk/gov/hmrc/hecapplicantfrontend/config/AppConfig.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/CtutrAttempts.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/HECSession.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/ids/GGCredId.scala
app/uk/gov/hmrc/hecapplicantfrontend/repos/CtutrAttemptsStore.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/CtutrAttemptsService.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
conf/application.conf
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/models/HECSessionDataSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/repos/CtutrAttemptsStoreImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/CtutrAttemptsServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/utils/Fixtures.scala

Details in ticket -> https://jira.tools.tax.service.gov.uk/browse/HEC-1426

HEC-1426 CTUTR attempts blocking functionality

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNController.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala

Details in ticket -> https://jira.tools.tax.service.gov.uk/browse/HEC-1427

HEC-1427 Check if CRN is blocked in CRN submit endpoint

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNController.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/CtutrAttempts.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/CtutrAttemptsService.scala
app/uk/gov/hmrc/hecapplicantfrontend/util/TimeUtils.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/TooManyCtutrAttempts.scala.html
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/repos/CtutrAttemptsStoreImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/CtutrAttemptsServiceImplSpec.scala

Details in ticket -> [HEC-1461](https://jira.tools.tax.service.gov.uk/browse/HEC-1461)

HEC-1461 Implement too-many-ctutr-attempts page

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/ConfirmIndividualDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/StartController.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/HECSession.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckService.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/ConfirmIndividualDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/StartControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/models/HECSessionDataSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/utils/Fixtures.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1577

HEC-1577 dont display confirm individual details page

---

app/uk/gov/hmrc/hecapplicantfrontend/connectors/HECConnector.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxSituationController.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/RetrievedJourneyData.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/ApplicantDetails.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/HECTaxCheckData.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/HECTaxCheckSource.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/TaxDetails.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/company/CTAccountingPeriod.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/company/CTStatus.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/company/CTStatusResponse.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/individual/SAStatus.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/hecTaxCheck/individual/SAStatusResponse.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckService.scala
app/uk/gov/hmrc/hecapplicantfrontend/testonly/models/SaveTaxCheckRequest.scala
app/uk/gov/hmrc/hecapplicantfrontend/testonly/services/JourneyToLoginDataTransformer.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/helpers/SummaryRows.scala
test/uk/gov/hmrc/hecapplicantfrontend/connectors/HECConnectorImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CheckYourAnswersControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxSituationControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/models/HECTaxCheckDataSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/testonly/connectors/HECConnectorImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/testonly/controllers/JourneyStarterControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/testonly/services/HECServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/testonly/services/JourneyToLoginDataTransformerImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/utils/Fixtures.scala

| Before      | After |
| ----------- | ----------- |
|  <img width="349" alt="Screenshot 2021-12-09 at 11 37 43" src="https://user-images.githubusercontent.com/13031285/145389878-9ae66735-899b-44b6-adee-492722a0cf7b.png">| <img width="348" alt="Screenshot 2021-12-09 at 11 37 24" src="https://user-images.githubusercontent.com/13031285/145389936-c5cbe36f-8729-498c-893e-3abfd092e047.png">|

Reorganise models

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/LicenceDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/MaxTaxChecksLimitExceeded.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/LicenceDetailsControllerSpec.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1632

HEC-1632 too many tax check attempts page and test cases

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsController.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsControllerSpec.scala

Updated the look back period logic with test cases. 
-Some refactoring is also done for the test cases, Rest of the refactoring will do in separate PR

look back period logic change

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/EmailAddressConfirmedController.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/HECTaxCheck.scala
app/uk/gov/hmrc/hecapplicantfrontend/models/emailSend/EmailParameters.scala
app/uk/gov/hmrc/hecapplicantfrontend/util/FormUtils.scala
conf/application.conf
test/uk/gov/hmrc/hecapplicantfrontend/connectors/SendEmailConnectorImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CheckYourAnswersControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/EmailAddressConfirmedControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TaxCheckCompleteControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/SendEmailServiceImplSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/TaxCheckServiceImplSpec.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1703

Hec 1703 email template

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/ProblemSendingEmailController.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/ProblemSendingEmail.scala.html
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/ProblemSendingEmailControllerSpec.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1770

HEC-1770 email cannot send page

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/TooManyEmailVerificationAttemptController.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/TooManyEmailVerificationAttempts.scala.html
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TooManyEmailVerificationAttemptControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/TooManyPasscodeVerificationControllerSpec.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1781

Hec 1781 too many email

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/VerificationPasscodeExpiredController.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/VerificationPasscodeExpired.scala.html
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/VerificationPasscodeExpiredControllerSpec.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1784

Hec 1784 passcode expire

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/CannotSendVerificationPasscodeController.scala
app/uk/gov/hmrc/hecapplicantfrontend/services/JourneyService.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/CannotSendVerificationPasscoode.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CannotSendVerificationPasscodeControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/services/JourneyServiceImplSpec.scala

ticket details -> https://jira.tools.tax.service.gov.uk/browse/HEC-1780

HEC-1780 exit page for bad emil request

---

app/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNController.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsController.scala
app/uk/gov/hmrc/hecapplicantfrontend/controllers/VerifyEmailPasscodeController.scala
app/uk/gov/hmrc/hecapplicantfrontend/util/ControllerUtils.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CompanyDetailsControllerSpec.scala
test/uk/gov/hmrc/hecapplicantfrontend/controllers/VerifyEmailPasscodeControllerSpec.scala

Adding ControllerUtils with noXssChars function
enterCtutreForm now uses noXssChars
crnForm now uses noXssChars
verifyPasscodeForm now uses noXssChars
Adding test for enterCtutr in CompanyDetailsController
Adding test for verifyPasscodeForm in VerifyEmailPasscodeController
No test for crnForm in CRNController because there is already one called:
"the submitted value contains characters which are not letters or digits"

DDCYLS-3056

---

app/uk/gov/hmrc/hecapplicantfrontend/views/CompanyRegistrationNumber.scala.html
conf/messages
conf/messages.cy
test/uk/gov/hmrc/hecapplicantfrontend/controllers/CRNControllerSpec.scala

Amending the company registration number page to update the content to the new template. Welsh translation also updated to align.

DDCYLS-3919 - Amending the company registration number page to update the content 

---

README.md

DDCYLS-6378 - Updating ReadMe

---

precheck.sh
project/AppDependencies.scala

DDCYLS-6652: added precheck script.

---

app/uk/gov/hmrc/hecapplicantfrontend/config/AppConfig.scala
app/uk/gov/hmrc/hecapplicantfrontend/views/Layout.scala.html
conf/messages
conf/messages.cy

DDCYLS-6764: Amending timeout wording and navigation for GDS

DDCYLS-6764: Amending timeout wording and navigation for GDS
